
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vpprejina/spring-cloud-config-server
         # username: vpprejina
         # password: Rejina@12345
          search-paths:
          - app* 
          
